services:
  postgres:
    image: postgres:latest
    container_name: postgres_template_api
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "9543:5432"
    volumes:
      - template_api_postgres_data:/var/lib/postgresql/data
volumes:
  template_api_postgres_data:
